# Generated by Django 2.2.1 on 2019-07-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images_and_videos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
