# Generated by Django 2.2.1 on 2019-07-28 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images_and_videos', '0002_delete_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail_aws_path', models.CharField(max_length=256)),
                ('banner_aws_path', models.CharField(max_length=256)),
                ('video_aws_path', models.CharField(max_length=256)),
                ('project_type', models.CharField(choices=[('G', 'General'), ('S', 'Sketchbook'), ('E', 'Exhibition'), ('T', 'Teaching')], default='G', max_length=13)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_aws_path', models.CharField(max_length=256)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images_and_videos.Project')),
            ],
        ),
    ]
