# Generated by Django 2.2.3 on 2019-07-29 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.FileField(upload_to='')),
                ('banner', models.FileField(upload_to='')),
                ('video', models.FileField(upload_to='')),
                ('project_type', models.CharField(choices=[('G', 'General'), ('S', 'Sketchbook'), ('E', 'Exhibition'), ('T', 'Teaching')], default='G', max_length=13)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
